# Generated by Django 5.2 on 2025-09-19 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_post1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post1',
        ),
    ]
